@port = {{$dotenv PORT}}
@baseUrl = http://localhost:{{port}}
@MONGO_URL
### Single Stock 15 min 
GET {{baseUrl}}/api/singleStock?stock=AAPL

### Single Stock 15 min 
GET {{baseUrl}}/api/singleStock?stock=AAPL

### Add Stock 
POST {{baseUrl}}/api/stocks HTTP/1.1
Content-Type: application/json 

{"symbol": "TSLA"}

### GET Stock out of DB
GET {{baseUrl}}/api/stocks HTTP/1.1  
Accept: application/json

###Delete Stock out of DB
DELETE {{baseUrl}}/api/stocks/ HTTP/1.1
Accept: application/json

{"symbol": "AAPL"}


